version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend-docker
    restart: always
    environment:
      - REACT_APP_BACKEND_ENDPOINT=${BACKEND_ENDPOINT}
    links:
      - backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend-docker
    restart: always